# Documentation: http://docs.travis-ci.com/user/languages/julia/
language: julia
codecov: true
coveralls: true

os:
  - linux
  - osx
  - windows

julia:
  - 1.0
  - 1.5
  - nightly

matrix:
  allow_failures:
  - julia: nightly

notifications:
    email:
      recipients:
        - donsadit@gmail.com

    on_success: change  # options: [always|never|change] default: always
    on_failure: always  # options: [always|never|change] default: always
    on_start: never     # options: [always|never|change] default: alway

env:
  global:
    - DISABLE_AMEND_COVERAGE_FROM_SRC=yes

# uncomment the following lines to override the default test script
script:
#  - if [[ -a .git/shallow ]]; then git fetch --unshallow; fi
#  the following early package addition avoids long waits for julia's register updates
  - julia -e 'using Pkg; pkg"add https://github.com/sadit/SimilaritySearch.jl"'
  - julia -e 'using Pkg; pkg"add https://github.com/sadit/KCenters.jl"'

after_success:
  - julia -e 'using Pkg; import KNearestCenters; joinpath(dirname(pathof(KNearestCenters)), ".."); Pkg.add("Coverage"); using Coverage; Coveralls.submit(Coveralls.process_folder())'
  - julia -e 'using Pkg; import KNearestCenters; joinpath(dirname(pathof(KNearestCenters)), ".."); Pkg.add("Coverage"); using Coverage; Codecov.submit(Codecov.process_folder())'
